error: add module for error types and utilities
We plan to introduce interfaces which communicate (re-)allocation
failures to users of this library. For reporting errors, we'll need
error types, which should reside in a dedicated module.